default:
  # 服务监听端口
  listen: 8090
  # 日志类型，支持 stdout, stderr 和 file, 默认为 stdout
  log_type: stdout
  # 日志级别，支持 INFO, WARN 和 ERROR, 默认为 INFO
  log_level: INFO
  # 日志路径，在日志类型为 file 的时候生效
  log_dir: /var/zaplog/pixiu